### ISSUE TITLE
Requests don't error out properly

### ISSUE THREAD

**Issue by nuudles** [AmarJayR/VoatKit#2]
The current API is down with a 403 error, but the requests don't appear to be returning with errors. Instead we're getting back an array of nonsense and the error parameter of the completion block is nil.

**Comment by AmarJayR** [comment]
This issue is fixed as of commit 4a213f969edca64a05b897b91de6ff7aaaa59a2c. The problem was that the VKResponseSerializer was checking if the response was JSON before checking for any HTTP status code errors. Since the voat developer site is running on Azure Websites, the error response was returning a full HTML page, and VKResponseSerializer saw that it wasn't a JSON response so it returned an error before checking the HTTP status codes.

I don't think this will be a problem on the main voat site since voat.co isn't run on Microsoft Azure, but I have fixed it anyway.

I have not fully implemented voat API errors since they have not released a full list of errors in their documentation. 

Please let me know if this issue is resolved at your end as well.

Thanks,
-Amar
